import type { Product } from '../types';

export const mockProducts: Product[] = [
  {
    id: 'p1',
    name: 'Apple iPhone 16 Pro Max',
    subtitle: '全新A18 Pro芯片 | 钛金属设计',
    description: '搭载A18 Pro芯片，全新4800万像素融合式摄像头系统，支持USB-C接口，钛金属设计更坚固轻盈。',
    price: 9999,
    originalPrice: 10999,
    stock: 500,
    sales: 12340,
    images: [{ id: 'img1', url: '', alt: 'iPhone 16 Pro Max', isPrimary: true }],
    categoryId: 'c1',
    specs: [
      { name: '品牌', value: 'Apple' },
      { name: '型号', value: 'iPhone 16 Pro Max' },
      { name: '存储', value: '256GB' },
      { name: '颜色', value: '原色钛金属' },
    ],
    tags: ['新品', '热卖'],
    rating: 4.9,
    reviewCount: 8520,
    isNew: true,
    isHot: true,
    createdAt: '2026-05-01',
  },
  {
    id: 'p2',
    name: '华为 Mate 70 Pro+',
    subtitle: '麒麟9100 | 卫星通信',
    description: '搭载自研麒麟9100芯片，支持天通卫星通信，XMAGE影像系统，超可靠昆仑玻璃。',
    price: 7999,
    originalPrice: 8999,
    stock: 300,
    sales: 9870,
    images: [{ id: 'img2', url: '', alt: '华为 Mate 70 Pro+' }],
    categoryId: 'c1',
    specs: [
      { name: '品牌', value: '华为' },
      { name: '型号', value: 'Mate 70 Pro+' },
      { name: '存储', value: '512GB' },
    ],
    tags: ['新品', '5G'],
    rating: 4.8,
    reviewCount: 6230,
    isNew: true,
    createdAt: '2026-04-15',
  },
  {
    id: 'p3',
    name: 'MacBook Pro 16英寸 M4 Max',
    subtitle: 'M4 Max芯片 | 48GB内存',
    description: 'Apple M4 Max芯片，16核中央处理器，40核图形处理器，48GB统一内存，1TB固态硬盘。',
    price: 24999,
    originalPrice: 26999,
    stock: 150,
    sales: 4520,
    images: [{ id: 'img3', url: '', alt: 'MacBook Pro 16' }],
    categoryId: 'c2',
    specs: [
      { name: '品牌', value: 'Apple' },
      { name: '处理器', value: 'M4 Max' },
      { name: '内存', value: '48GB' },
      { name: '存储', value: '1TB' },
    ],
    tags: ['新品'],
    rating: 4.9,
    reviewCount: 2100,
    isNew: true,
    createdAt: '2026-03-20',
  },
  {
    id: 'p4',
    name: '小米电视 S Pro 85英寸',
    subtitle: 'Mini LED | 144Hz高刷',
    description: '85英寸Mini LED旗舰电视，144Hz高刷新率，4K超高清分辨率，支持杜比视界全景声。',
    price: 5999,
    originalPrice: 7999,
    stock: 200,
    sales: 7650,
    images: [{ id: 'img4', url: '', alt: '小米电视 S Pro' }],
    categoryId: 'c3',
    specs: [
      { name: '品牌', value: '小米' },
      { name: '尺寸', value: '85英寸' },
      { name: '面板', value: 'Mini LED' },
      { name: '刷新率', value: '144Hz' },
    ],
    tags: ['热卖', '618'],
    rating: 4.7,
    reviewCount: 4320,
    isHot: true,
    createdAt: '2026-02-10',
  },
  {
    id: 'p5',
    name: 'Nike Air Jordan 1 Retro High OG',
    subtitle: '经典复刻 | 芝加哥配色',
    description: 'Air Jordan 1 经典芝加哥配色复刻版，头层牛皮鞋面，Air-Sole气垫缓震。',
    price: 1299,
    originalPrice: 1499,
    stock: 800,
    sales: 15670,
    images: [{ id: 'img5', url: '', alt: 'Air Jordan 1' }],
    categoryId: 'c4',
    specs: [
      { name: '品牌', value: 'Nike' },
      { name: '系列', value: 'Air Jordan 1' },
      { name: '鞋码', value: '36-46' },
      { name: '适用人群', value: '男女同款' },
    ],
    tags: ['热卖', '经典'],
    rating: 4.8,
    reviewCount: 12300,
    isHot: true,
    createdAt: '2025-11-15',
  },
  {
    id: 'p6',
    name: '三只松鼠 坚果大礼包 2188g',
    subtitle: '每日坚果 | 年货送礼',
    description: '精选6种坚果组合，每日坚果科学配比，年货送礼佳品，2188g超大容量。',
    price: 138,
    originalPrice: 198,
    stock: 2000,
    sales: 45890,
    images: [{ id: 'img6', url: '', alt: '三只松鼠坚果礼包' }],
    categoryId: 'c5',
    specs: [
      { name: '品牌', value: '三只松鼠' },
      { name: '净含量', value: '2188g' },
      { name: '保质期', value: '240天' },
    ],
    tags: ['热卖', '618'],
    rating: 4.5,
    reviewCount: 35600,
    isHot: true,
    createdAt: '2026-01-01',
  },
  {
    id: 'p7',
    name: '珀莱雅 双抗精华液 30ml',
    subtitle: '抗氧抗糖 | 水润修护',
    description: '双抗精华液，抗氧抗糖二合一，水润修护肌肤屏障，改善暗沉粗糙。',
    price: 259,
    originalPrice: 329,
    stock: 1200,
    sales: 28760,
    images: [{ id: 'img7', url: '', alt: '珀莱雅双抗精华' }],
    categoryId: 'c6',
    specs: [
      { name: '品牌', value: '珀莱雅' },
      { name: '规格', value: '30ml' },
      { name: '适合肤质', value: '所有肤质' },
    ],
    tags: ['618'],
    rating: 4.6,
    reviewCount: 19800,
    createdAt: '2025-12-20',
  },
  {
    id: 'p8',
    name: 'Switch 2 游戏主机',
    subtitle: '新一代 | 支持4K',
    description: '任天堂Switch 2全新升级，支持4K游戏输出，8英寸LCD屏幕，Joy-Con 2手柄，向下兼容Switch游戏。',
    price: 3299,
    originalPrice: 3599,
    stock: 100,
    sales: 6780,
    images: [{ id: 'img8', url: '', alt: 'Switch 2' }],
    categoryId: 'c10',
    specs: [
      { name: '品牌', value: '任天堂' },
      { name: '屏幕', value: '8英寸LCD' },
      { name: '存储', value: '256GB' },
    ],
    tags: ['新品'],
    rating: 4.7,
    reviewCount: 2100,
    isNew: true,
    createdAt: '2026-05-10',
  },
  {
    id: 'p9',
    name: '戴森 V15 Detect 无绳吸尘器',
    subtitle: '激光探测 | 智能吸力调节',
    description: '戴森V15 Detect无线吸尘器，激光探测微尘，智能调节吸力，LCD屏幕实时显示清洁数据。',
    price: 4990,
    originalPrice: 5290,
    stock: 60,
    sales: 3450,
    images: [{ id: 'img9', url: '', alt: '戴森 V15' }],
    categoryId: 'c3',
    specs: [
      { name: '品牌', value: '戴森' },
      { name: '续航', value: '60分钟' },
      { name: '集尘容量', value: '0.76L' },
    ],
    tags: ['618'],
    rating: 4.8,
    reviewCount: 5670,
    createdAt: '2026-03-01',
  },
  {
    id: 'p10',
    name: '联想 ThinkPad X1 Carbon Gen 13',
    subtitle: '14英寸AI商务本 | 986g',
    description: '第13代X1 Carbon，搭载Intel酷睿Ultra处理器，14英寸2.8K OLED屏，仅986g超轻机身。',
    price: 10999,
    originalPrice: 12999,
    stock: 80,
    sales: 2340,
    images: [{ id: 'img10', url: '', alt: 'ThinkPad X1 Carbon' }],
    categoryId: 'c2',
    specs: [
      { name: '品牌', value: '联想' },
      { name: '处理器', value: 'Intel Core Ultra 7' },
      { name: '内存', value: '32GB' },
      { name: '重量', value: '986g' },
    ],
    tags: ['新品', '商务'],
    rating: 4.7,
    reviewCount: 890,
    isNew: true,
    createdAt: '2026-04-01',
  },
  {
    id: 'p11',
    name: '李宁 超轻 2026 跑鞋',
    subtitle: '轻量透气 | 䨻科技',
    description: '李宁超轻系列第17代跑鞋，䨻科技中底，轻量透气鞋面，确保每一步都轻盈舒适。',
    price: 499,
    originalPrice: 699,
    stock: 1500,
    sales: 9870,
    images: [{ id: 'img11', url: '', alt: '李宁 超轻2026' }],
    categoryId: 'c7',
    specs: [
      { name: '品牌', value: '李宁' },
      { name: '鞋码', value: '36-46' },
      { name: '技术', value: '䨻科技' },
    ],
    tags: ['热卖'],
    rating: 4.6,
    reviewCount: 7800,
    isHot: true,
    createdAt: '2026-02-28',
  },
  {
    id: 'p12',
    name: '《三体》全集精装版',
    subtitle: '刘慈欣 | 雨果奖作品',
    description: '刘慈欣科幻巨著《三体》全集精装版，包含《三体》《黑暗森林》《死神永生》三部曲。',
    price: 99,
    originalPrice: 168,
    stock: 3000,
    sales: 56780,
    images: [{ id: 'img12', url: '', alt: '三体全集' }],
    categoryId: 'c8',
    specs: [
      { name: '作者', value: '刘慈欣' },
      { name: '出版社', value: '重庆出版社' },
      { name: '册数', value: '3册' },
    ],
    tags: ['经典'],
    rating: 4.9,
    reviewCount: 68900,
    createdAt: '2024-06-01',
  },
];
